name: Code Styles

on: [push, pull_request]

env:
    VENDOR: /home/runner/.composer/vendor

jobs:
    php-sniffer:
        strategy:
            matrix:
                php-versions: [ '7.4' ]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            # PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl
#                  tools: php-cs-fixer, phpunit
            - name: Get composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  # Use composer.json for key, if composer.lock is not committed.
                  # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - run: composer global require lyrasoft/cli
            - run: $VENDOR/bin/lyra sniffer sync
            - name: Run CS Check
              run: $VENDOR/bin/phpcs src --standard=$VENDOR/lyrasoft/cli/tmp/development-tools/Sniffer/Windwalker -n --extensions=php
